- name: Экспорт текущей политики безопасности
  ansible.windows.win_shell: secedit /export /cfg C:\secpol.cfg

- name: Изменить политику сложности пароля в конфигурации безопасности
  ansible.windows.win_shell: |
    (Get-Content C:\secpol.cfg) -replace "PasswordComplexity = 1", "PasswordComplexity = 0" | Set-Content C:\secpol.cfg

- name: Применить измененную политику безопасности
  ansible.windows.win_shell: secedit /configure /db C:\Windows\security\local.sdb /cfg C:\secpol.cfg /areas SECURITYPOLICY

- name: Удалить файл конфигурации безопасности
  ansible.windows.win_file:
    path: C:\secpol.cfg
    state: absent

- name: Установить пароль администратора
  ansible.windows.win_user:
    name: Administrator
    password: vagrant
    update_password: always

- name: Установить AD-Domain-Services
  ansible.windows.win_feature:
    name:
      - AD-Domain-Services
      - RSAT-AD-PowerShell
      - RSAT-AD-AdminCenter
    state: present
    include_management_tools: yes
    
- name: Развернуть ADDS
  ansible.windows.win_shell: |
    Import-Module ADDSDeployment
    Install-ADDSForest `
      -SafeModeAdministratorPassword (ConvertTo-SecureString '{{ admin_password }}' -AsPlainText -Force) `
      -DomainName "example.com" `
      -CreateDnsDelegation:$false `
      -DatabasePath "C:\Windows\NTDS" `
      -DomainMode "7" `
      -DomainNetbiosName "EXAMPLE" `
      -ForestMode "7" `
      -InstallDns:$true `
      -LogPath "C:\Windows\NTDS" `
      -SysvolPath "C:\Windows\SYSVOL" `
      -Force:$true
  args:
    executable: powershell

- name: Перезагрузить машину после установки AD-Domain-Services
  ansible.windows.win_reboot:
    reboot_timeout: 600  # Установите тайм-аут в секундах для перезагрузки
